# Makefile for IFS run
#========================================================================

# Vertical velocities
#------------------------------------------------------------------------
# fl01  = -Dw_2dim       # Turn off vertical velocities.
fl01  = -Dw_3dim        # Compute the vertical velocity.

# Grid type
#------------------------------------------------------------------------
fl02  = -DA_grid        # Input data on a A grid

# Time integration scheme
#------------------------------------------------------------------------
fl03 = -Dtime_analytical

#========================================================================
ORM_FLAGS= -D$(PROJECT) \
$(fl01)$(fl02)$(fl03)
